# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Berlin 2015"
email: "team@devfest-berlin.de"
description: "DevFest Berlin "
baseurl: ""
url: "https://2015.devfest-berlin.de/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-66916229-1"
googleAnalyticsSiteUrl: "devfest-berlin.de"
siteVerification: "-ArvK1Z6viSO7jd4DpG1KujHHXxSNSedS8lvtUGL7kE"

# Organizer Info
organizerName: "The 3 GDGs of Berlin"
organizerAlternateName: "GDG Berlin, GDG Berlin Android &amp; GDG Berlin Golang"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "team@devfest-berlin.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdg-berlin.de"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, berlin"
twitterAccount: "@GDGBerlin"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://conference.devfest-berlin.de/en/devfestberlin2015/cfp/session/new"
c4sponsorsUrl: "https://drive.google.com/file/d/0B63FtzFoCw0_aHJYeTBoWjE5R1E/view?usp=sharing"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/code-of-conduct/", text: "Code of Conduct"}
# - {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "https://plus.google.com/+DevFestBerlin", text: "Google+ Page"}
bottomNavigationLinks:
 - {link: "/#tickets", text: "Buy a ticket"}
rightNavigationButtons:
 - {link: "/#tickets", text: "Buy a ticket"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest <typeout>"
eventDate: "13/14/15 November 2015"
typeoutTextValues: '"Karlsruhe?", "Hamburg?", "Vienna?", "Malta?", "Zurich?", "Brussels?", "Berlin 2015!"'
typeoutFallback: "Berlin 2015"
heroButtons:
 - {permalink: "/schedule", text: "See the schedule"} 
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About DevFest Berlin"
aboutBlock:
 - {title: "Workshops", image: "workshop.jpg", text: "Half day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "36", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "24", specialCharacter: "+", info: "speakers", detail: "from the local community and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Our speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "ImmobilienScout24"
eventLocationLink: "http://developer.immobilienscout24.de/about-us/"
eventStreetAddress: "Andreasstr. 10"
eventAddressLocality: "Berlin"
eventAddressLocalityRegion: "Berlin"
eventPostalCode: "10243"
eventAddressCountry: "Germany"
eventStartTime: "2015-11-13T15:00"
eventDoorTime: "14:00"
eventEndTime: "2015-11-15T18:00"
eventPlaceCoordinates: "52.512594, 13.431108"
mapCenterCoordinates: "52.511951, 13.433307"
mapMobileCenterCoordinates: "52.512594, 13.431108"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "ImmobilienScout24 Headquarters"
venueFeatures: ["3 rooms with top-notch equipment", "Café area for chats and chill out", "Easily accessible by public transport"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfestBerlin"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Get your ticket NOW!"
ticketsInfo: "Tickets grant access to all conference sections on all 3 days, incl. coffee breakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/116495772997450383126", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGBerlin", icon: "twitter"}
 - {link: "https://twitter.com/intent/user?screen_name=BerlinDroid", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.meetup.com/gdgberlin/", text: "GDG Berlin Meetup"}
   - {link: "http://www.meetup.com/GDG-Android-in-Berlin/", text: "GDG Berlin Android Meetup"}
   - {link: "http://www.meetup.com/golang-users-berlin/", text: "GDG Berlin Golang Meetup"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:team@devfest-berlin.de", text: "team@devfest-berlin.de"}
 -
  title: "FAQ"
  links:
   - {permalink: "/code-of-conduct/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest News"
blogCommentsEnabled: false
#discusShortName: "devfestBerlin"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "52.512594, 13.431108"
logisticsMapMobileCenterCoordinates: "52.512594, 13.431108"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Berlin"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airports Tegel [TXL] and Schönefeld [SXF] are right at the city border. They are easily reachable by car, public transport or taxi. More information is available at <a href="http://www.berlin-airport.de/en/">the centrail airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Berlin. So you can find your way in Google Maps, the closest station is <strong>"Ostbahnhof"</strong>.<br/><br/>Moreover, you can download any of the offline public transit apps available for Berlin, e.g. <a href="https://play.google.com/store/apps/details?id=de.schildbach.oeffi">Oeffi</a>.'}
 - {title: "Hotels", information: 'Berlin has lots of great (and bad) hotels and hostels.<br/><br/>The closest hotel is <a href="http://www.accorhotels.com/gb/hotel-3108-ibis-berlin-ostbahnhof/index.shtml">Ibis</a> and a close hostel is <a href="http://www.aohostels.com/en/berlin/berlin-mitte/">A&amp;O</a>.'}
directionDetailsWideCards:
 # -
 #  title: "Questions?"
 #  subCards:
 #   -
 #    title: "Hotels"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #   -
 #    title: "Registration"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #   -
 #    title: "Attendance Details"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
